# This variable requests the highest version of
# Visual Studio to be installed. Previous versions
# will also be available and work. So, choosing 2015 here makes
# available both `msvs_toolset: 12` (from Visual Studio 2013)
# and `msvs_toolset: 14` (from Visual Studio 2015)
# Note/TODO: it is not yet confirmed that earlier versions work with the the `Visual Studio 2017` os image.
os: Visual Studio 2017
platform:
  - x64
configuration:
  - Release
matrix:
  fast_finish: true
environment:
  matrix:
    - nodejs_version: 12
install:
  - .\scripts\winci.bat
build: OFF
test: OFF
deploy: OFF

